#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require 'optparse'
require 'pp'

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: check_mpstat [options]"
  opts.on("-iINTERVAL", "--interval=INTERVAL", "Time in seconds to sample") {|n| options[:interval] = n.to_i}
end.parse!

options[:interval] ||= 2
raise OptionParser::InvalidOption, "Interval cant be 0" if options[:interval] == 0

input = `mpstat 1 #{options[:interval]}`
fields = input.split("\n")[2].split(/ +/)
fields.map!{|f| f.sub(/^%/,"")}
values = input.split("\n").last.split(/ +/)

data = Hash.new(0)
fields.each_with_index do |field, i|
  data[field] = values[i].gsub(",",".").to_f
end

data['total'] = 100.0 - data['idle']

output = ""
perfdata = ""
%w"usr nice sys iowait irq soft steal guest total".each do |key|
  output << "#{key}: #{data[key].round(2)}% // "
  perfdata << "#{key}=#{data[key].round(2)}% "
end

print "#{output} | #{perfdata}"
